<a href="https://colab.research.google.com/github/jeevan-nh/Google-collab-udemy-DL-course/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [0]:
dataset.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [0]:
X[6]

array([822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Country column
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
X = X[:, 1:]

# Gender column
ct = ColumnTransformer([("Gender_1", OneHotEncoder(), [3])], remainder = 'passthrough')
X = ct.fit_transform(X)


In [0]:
X = X[:, 1:]

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
X_train[0]

array([0.0, 0.0, 1.0, 667, 34, 5, 0.0, 2, 1, 0, 163830.64], dtype=object)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initialising the ANN
classifier = Sequential()

In [0]:
# Adding the input layer and the first hidden layer
#output_dim or units is basically (inputcol + outputcol)/2
#activation formular is rectifier
#kernal_init is basically initilizing the weights to the synpase
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [0]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [0]:
#adding the output layer
#change the activation function to sigmoid function
#if the dependent variable is catagorical and has more the 2 catagory then we need to use scetmoid insted to sigmoid
classifier.add(Dense(output_dim = 1,init ='uniform',activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#compling the ANN
#optimizer is function used to find the best weights
#loss is function that is used to find the optimal weights we used 'binary_crossentropy' pr ''categorial_crossentropy'
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
#running the ANN 
classifier.fit(X_train,y_train,batch_size=10 , epochs=100)




Epoch 1/100





8000/8000 [==============================] - 2s 213us/step - loss: 0.4799 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4165 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4054 - acc: 0.8141
Epoch 4/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.3951 - acc: 0.8276
Epoch 5/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3865 - acc: 0.8307
Epoch 6/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.3796 - acc: 0.8375
Epoch 7/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3739 - acc: 0.8461
Epoch 8/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.3705 - acc: 0.8471
Epoch 9/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.3665 - acc: 0.8495
Epoch 10/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.3644 - acc

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1512,   83],
       [ 194,  211]])

In [0]:
(1538 + 147 ) / 2000

0.8425

Homework Instruction


Use our ANN model to predict if the customer with the following informations will leave the bank: 

    Geography: France
    Credit Score: 600
    Gender: Male
    Age: 40 years old
    Tenure: 3 years
    Balance: $60000
    Number of Products: 2
    Does this customer have a credit card ? Yes
    Is this customer an Active Member: Yes
    Estimated Salary: $50000

So should we say goodbye to that customer ?



In [0]:
new_pred = classifier.predict(sc.transform(np.array([[1.0,0.0,0.0,600,40,3,60000,2,1,1,50000]])))

In [0]:
new_pred = (new_pred > 0.5)
new_pred

array([[False]])

The Customer wont leave the bank.

**K-FOLD CROSS VALIDATION**



In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [0]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
  classifier.add(Dense(output_dim = 1,init ='uniform',activation='sigmoid'))
  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics=['accuracy'])
  return classifier

In [0]:
classifier = KerasClassifier(build_fn = build_classifier , batch_size = 10, nb_epoch = 100)

In [0]:
accuracy = cross_val_score(estimator = classifier ,X =  X_train, y = y_train, cv = 10, n_jobs= -1)

In [0]:
accuracy

array([0.78625   , 0.79      , 0.8       , 0.7825    , 0.81625   ,
       0.81      , 0.7875    , 0.80125   , 0.79875   , 0.79499999])

In [0]:
mean_accuracy = accuracy.mean()
var_accuracy = accuracy.std()
print(f'accuracy mean - {mean_accuracy} \naccuracy variance - {var_accuracy}')

accuracy mean - 0.7967499969154597 
accuracy variance - 0.010188841000707218


In [0]:
#improving the ANN
#Dropout Regularlizatoin to reduce overfitting
#p value should'nt be above 0.5 because this might casuse underfitting 
#from keras.layers import Dropout 
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
#classifier.add(Dropout(p = 0.1))
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#classifier.add(Dropout(p = 0.1))
#classifier.add(Dense(output_dim = 1,init ='uniform',activation='sigmoid'))

**Parameter Tunnig** 

This is basically used to improve the accuracy of the ANN by choosing the proper hyper parameter which can be used to improve the Accuracy.
This can be done by using the method called grid search.This is basically build the model by using different combination of the hyperparameter and ultimatly coming to a conclusion if the best combination if the hyperparameter.


In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [0]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
  classifier.add(Dense(output_dim = 1,init ='uniform',activation='sigmoid'))
  classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy',metrics=['accuracy'])
  return classifier

In [0]:
classifier = KerasClassifier(build_fn = build_classifier)
#HyperParameter dictonary
parameters = {'batch_size' : [25,32],
              'nb_epoch' : [100, 500],
              'optimizer' : ['adam' , 'rmsprop']}

In [0]:
grid_search = GridSearchCV(estimator= classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


Epoch 1/1
7200/7200 [==============================] - 1s 95us/step - loss: 0.5546 - acc: 0.7957
Epoch 1/1
7200/7200 [==============================] - 1s 106us/step - loss: 0.5514 - acc: 0.7961
Epoch 1/1
7200/7200 [==============================] - 1s 122us/step - loss: 0.5758 - acc: 0.7946
Epoch 1/1
7200/7200 [==============================] - 1s 118us/step - loss: 0.5626 - acc: 0.7975
Epoch 1/1
7200/7200 [==============================] - 1s 131us/step - loss: 0.5607 - acc: 0.7931
Epoch 1/1
7200/7200 [==============================] - 1s 143us/step - loss: 0.5668 - acc: 0.7929
Epoch 1/1
7200/7200 [==============================] - 1s 144us/step - loss: 0.5600 - acc: 0.7957
Epoch 1/1
7200/7200 [==============================] - 1s 157us/step - loss: 0.5493 - acc: 0.7947
Epoch 1/1
7200/7200 [==============================] - 1s 159us/step - loss: 0.5536 - acc: 0.7956
Epoch 1/1
7200/7200 [==============================] - 1s 177us/step - loss: 0.5491 - acc: 0.7961
Epoch 1/1
7200/7200 [

In [0]:
best_parameter = grid_search.best_params_
best_accuracy = grid_search.best_score_
print(f'best parameter - {best_parameter} \nbest accuracy - {best_accuracy}')

best parameter - {'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'} 
best accuracy - 0.796
